# Generated by Django 5.1.6 on 2025-03-05 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('ip_hash', models.CharField(editable=False, max_length=255, null=True)),
                ('session_id', models.CharField(editable=False, max_length=255, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polling_api.option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polling_api.poll')),
                ('voted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'voted_by')},
            },
        ),
    ]
