# Generated by Django 5.1.6 on 2025-03-08 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_api', '0003_alter_vote_ip_hash_alter_vote_session_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['id'], name='polling_api_id_6cdcff_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['created_by'], name='polling_api_created_42f033_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expire_date'], name='polling_api_expire__edc84b_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['title'], name='polling_api_title_53c46a_idx'),
        ),
    ]
